apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: backend
spec:
  selector:
    app: fastapi-backend
  ports:
    - port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      imagePullSecrets:
        - name: acr-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: fastapi
          image: genaiplatform2026.azurecr.io/genai-backend:sha-dcc20a6
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-secret
                  key: GROQ_API_KEY
            - name: VLLM_URL
              value: "http://vllm-service.ai:8000"
            - name: QDRANT_URL
              value: "http://qdrant-service.data:6333"
            - name: HF_HOME
              value: "/app/hf-cache"
            - name: HF_HUB_DISABLE_TOKEN
              value: "1"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "2"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: uploads
              mountPath: /app/uploads
            - name: history
              mountPath: /app/history
            - name: hf-cache
              mountPath: /app/hf-cache
      volumes:
        - name: tmp
          emptyDir: {}
        - name: uploads
          emptyDir: {}
        - name: history
          emptyDir: {}
        - name: hf-cache
          emptyDir: {}
